Controllers/EmployeeController.cs
using DomingoRoofWork.Models;
using DomingoRoofWork.Repository;
using System.Web.Mvc;

namespace DomingoRoofWork.Controllers
{
    public class EmployeeController : Controller
    {
        // Get: Employee/GetAllEmployees
        public ActionResult GetAllEmployees()
        {
            EmployeeRepo empRepo = new EmployeeRepo();
            ModelState.Clear();
            return View(empRepo.GetAllEmployees());
        }

        //Get: Employee/ReturnEmployeeView
        public ActionResult AddEmployee()
        {
            return View();
        }
        //Post: Employee/AddEmployee
        [HttpPost]
        public ActionResult AddEmployee(EmployeeModel emp)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    EmployeeRepo empRepo = new EmployeeRepo();
                    if (empRepo.AddNewEmployee(emp))
                    {
                        ViewBag.Message = "Employee details added successfully";
                    }
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

        //Get: Employee/Return EditEmployee View
        public ActionResult EditEmployee(string id)
        {
            EmployeeRepo empRepo = new EmployeeRepo();
            return View(empRepo.GetAllEmployees().Find(emp => emp.EmpNo == id));
        }
        //Post: Employee/EditEmployee
        [HttpPost]
        public ActionResult EditEmployee(string id, EmployeeModel obj)
        {
            try
            {
                EmployeeRepo empRepo = new EmployeeRepo();
                empRepo.UpdateEmployee(obj);
                return RedirectToAction("GetAllEmployees");
            }
            catch
            {
                return View();
            }
        }

        //Get: Employee/DeleteEmployee
        public ActionResult DeleteEmployee(string id)
        {
            try
            {
                EmployeeRepo empRepo = new EmployeeRepo();
                if (empRepo.DeleteEmployee(id))
                {
                    ViewBag.AlertMsg = "Employee detials deleted successfully";
                }
                return RedirectToAction("GetAllEmployees");
            }
            catch
            {

                return View();
            }
        }

        public ActionResult AddEmployeeToJobCard(string id)
        {
            EmployeeRepo empRepo = new EmployeeRepo();

            return View(empRepo.GetAllEmployees().Find(er => er.EmpNo == id));
        }

        [HttpPost]
        public ActionResult AddEmployeeToJobCard(string id, EmployeeModel obj)
        {
            try
            {
                EmployeeRepo empRepo = new EmployeeRepo();
                obj.EmpNo = id;
                empRepo.AddEmployeeToJobCard(obj);

                return RedirectToAction("GetAllEmployees");
            }
            catch
            {
                return View();
            }
        }

    }
}

Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DomingoRoofWork.Models;
using DomingoRoofWork.Repository;

namespace DomingoRoofWork.Controllers
{
    public class InvoiceController : Controller
    {
        //View all of the available invoices
        public ActionResult GetAllInvoices()
        {
            InvoiceRepo invoices = new InvoiceRepo();
            ModelState.Clear();
            return View(invoices.GetAllInvoices());
        }

        public ActionResult InvoiceDetails(int id)
        {
            InvoiceRepo invoice = new InvoiceRepo();

            return View(invoice.GetInvoiceDetails(id).Find(inv => inv.JobCardNumber == id));
        }
    }
}

Controllers/JobCardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DomingoRoofWork.Models;
using DomingoRoofWork.Repository;

namespace DomingoRoofWork.Controllers
{
    public class JobCardController : Controller
    {
        public ActionResult GetAllJobCards()
        {
            JobCardRepo jobCard = new JobCardRepo();
            ModelState.Clear();
            return View(jobCard.GetJobCards());
        }

        //Create new Job Card 
        public ActionResult CreateJobCard()
        {
            return View("");
        }

        [HttpPost]
        public ActionResult CreateJobCard(JobCardModel jobCard)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    JobCardRepo jobCardRepo = new JobCardRepo();
                    if (jobCardRepo.AddNewJobCard(jobCard))
                    {
                        ViewBag.Message = "Employee details added successfully";
                    }
                }
                ModelState.Clear();
                return View();
            }
            catch
            {

                return View();
            }
        }
    }
}

Controllers/JobTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DomingoRoofWork.Models;
using DomingoRoofWork.Repository;

namespace DomingoRoofWork.Controllers
{
    public class JobTypeController : Controller
    {
        // GET: JobType
        public ActionResult ViewJobTypes()
        {
            JobTypeRepo jtRepo = new JobTypeRepo();
            ModelState.Clear();
            return View(jtRepo.ViewJobTypes());
        }

        // GET: JobType/Edit/5
        public ActionResult UpdateDailyRate(int id)
        {
            JobTypeRepo jtRepo = new JobTypeRepo();

            return View(jtRepo.ViewJobTypes().Find(jt => jt.JobTypeID == id));
        }

        // POST: JobType/Edit/5
        [HttpPost]
        public ActionResult UpdateDailyRate(int id, JobTypeModel obj)
        {
            try
            {
                JobTypeRepo jtRepo = new JobTypeRepo();
                obj.JobTypeID = id;
                jtRepo.UpdateJobType(obj);

                return RedirectToAction("ViewJobTypes");

            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Domingo Roof Works</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Domingo Roof Works", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li> @Html.ActionLink("View Employees", "GetAllEmployees", "Employee")</li>
                    <li> @Html.ActionLink("Job Cards", "GetAllJobCards", "JobCard")</li>
                    <li> @Html.ActionLink("View Job Types", "ViewJobTypes", "JobType")</li>
                    <li> @Html.ActionLink("Invoices", "GetAllInvoices", "Invoice")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Created by Bongani Brendon Gumbo</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>